# Generated by Django 3.2.3 on 2021-05-27 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ecomCore.utils_root.image_name_creator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='no bio yet')),
                ('avatar', models.ImageField(default='default.jpg', upload_to=ecomCore.utils_root.image_name_creator.customer_image_name)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
